tasks:
  build:
    image: node:8
    command:
      - npm
    args:
      - install
  test:
    image: node:8
    command:
      - npm
    args:
      - test
  echo:
    image: node:8
    command:
      - echo
    args:
      - "hello world"
